# This will run on Travis' 'new' container-based infrastructure
sudo: false

language: c

os: linux

compiler: gcc

# Blacklist
branches:
    only:
        - master

          # Install dependencies
addons:
    apt:
        packages:
            - lua5.2
            - cmake

                # Build your code e.g. by calling make
script:
    - git submodule init
    - git submodule update
    - mkdir build
    - cd build
    - cmake ..
    - make

